import logging
 
logger = logging.getLogger(__name__)
 
 
def complete(prompt: str, user_content: str) -> dict:
    """Return a hardcoded response. Used for local development when USE_STUB_CLIENT=true."""
    logger.warning("Stub client active — returning hardcoded response. Do not use in production.")
    return {
        "summary": "This is a stub summary returned by the local stub client.",
        "key_points": [
            "Stub key point one.",
            "Stub key point two.",
        ],
        "risks": [
            "Stub risk: this response is hardcoded and not generated by Azure OpenAI.",
        ],
    }
